import '../styles/globals.css'
import Navigation from 'src/components/Navigation'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js'
}

export default function RootLayout ({ children }) {
  return (
    <html lang='en'>
      <head>
        <title>First NextJS App</title>
      </head>
      <body>
        <Navigation />
        {children}
      </body>
    </html>
  )
}
